General fixes
Eliecer66/template-training pull request #4
Opened 2022-07-29 17:47 UTC by Eliecer66

I made a few repairs to the general code. If this branch is ok. The next step will be to apply Media Query.

2022-07-29 18:14 UTC, JorgEdmundo requested changes

2022-07-29 18:14 UTC, JorgEdmundo commented on css/styles.css
> +    padding:36px;
agrega un espacio después de los dos puntos.
```suggestion
    padding: 36px;
```

2022-07-29 18:14 UTC, JorgEdmundo commented on css/styles.css
> +    font-size: 2.1em;
En el `body` usaste `px` elije uno o el otro y mantente consistente.

2022-07-29 18:14 UTC, JorgEdmundo commented on css/styles.css
> +    margin: 0% 0% 0% 13%;
```suggestion
    margin: 0 0 0 13%;
```

2022-07-29 18:14 UTC, JorgEdmundo commented on css/styles.css
> +        font-size:3em;
Agrega un espacio después de los dos puntos.
```suggestion
        font-size: 3em;
```

2022-07-29 18:14 UTC, JorgEdmundo commented on index.html
> +        <div><input type="checkbox" name="recordatorio"><span>Remember me on this computer</span></div>
```suggestion
        <div>
          <input type="checkbox" name="recordatorio">
          <span>Remember me on this computer</span>
        </div> 
```

2022-07-30 14:27 UTC, Eliecer66 commented on css/styles.css
> +    font-size: 2.1em;
Uso `px` en el body porque ese es el tamaño de comparacion para el texto general de la pagina, asi solo cambio el tamaño de la fuente en el body en `px` y se aplica porcentualmente a los demas textos a traves de la unidad `em`.

2022-08-01 07:35 UTC, JorgEdmundo approved these changes

2022-08-01 07:38 UTC, JorgEdmundo commented
Good job bro! this is ready to merge.

2022-08-05 16:08 UTC, merged